# -*- coding: utf-8 -*-
"""Number Guessing Game.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1r75boD-mXRNPt28K6NsxyiGgXd4uaREI
"""

import random

def guess_the_number():
    number = random.randint(1, 1000)
    attempt = 0
    print("Welcome to the Number Guessing Game!")

    while True:
        try:
            guess = int(input("Guess a number between 1 to 1000: "))
            attempt += 1
            if guess == number:
                print(f"🎉 Congratulations! You guessed the number {number} in {attempt} attempts.")
                break
            elif guess < number:
                print("📉 Too low! Try again.")
            else:
                print("📈 Too high! Try again.")
        except ValueError:
            print("⚠️ Invalid input. Please enter a valid number.")

guess_the_number()

